### ISSUE TITLE
project3-path.find 問題

### ISSUE THREAD

**Issue by RobinJLin** [RobinJLin/PythonStudyGroupProjects#1]
project3 的 `electionPic.py` 檔案中，
line 150 是
```python
        title = path.find("{http://www.w3.org/2000/svg}title"
```

這句的 title 是 none 所以最後的結果都沒有改顏色
請問可以怎麼修正

**Comment by ZS-Yang-TW** [comment]
你的 Blank_Taiwan_map.svg 有問題，請重新到專案練習那邊[重新下載](https://www.notion.so/SVG-24a09b105989439496e706bf897602be?pvs=4#57ad8bd212a5419f9ea89bfb2133cfde)看看～

或是直接按這裡：
https://github.com/RobinJLin/PythonStudyGroupProjects/assets/95480878/2522d773-8e02-4ef7-8bb5-338f4288e2e3

剛剛跑了一下，部分城市的顏色沒有順利填上。找機會再檢查一下～

**Comment by RobinJLin** [comment]
我找到地圖有些區域沒有填色了！
是因為HSL 值 轉乘 HEX 色碼，有 0 開頭的色碼沒有多補一個零
例如：
`'花蓮縣': '#06deb'` ==> 花蓮縣的色碼開頭少一個 0 

只要把 `f"#{r:x}{g:x}{b:x}"` 改成 `f"#{r:02x}{g:x}{b:x}"` 就可以解決了
